from enum import Enum

class Functionality(Enum):
    SEND_FUNCTIONALITY = 'SEND_FUNCTIONALITY'
    SHOW_TIME = 'SHOW_TIME'
    SEARCH_PERSON_INFO = 'SEARCH_PERSON_INFO'
    MAKE_FILE = 'MAKE_FILE'
    DOWNLOAD_GIFS = 'DOWNLOAD_GIFS'
    TELL_JOKE_OF_THE_DAY = 'TELL_JOKE_OF_THE_DAY'
    SEND_EXIT = 'SEND_EXIT'
